// Preset color palettes. Every value maps to a CSS custom property,
// so switching palettes recolors the whole site (including the
// generative artwork, which is drawn with these variables).
export const PALETTES = [
  {
    id: 'gallery',
    name: 'Gallery',
    note: 'White / black — house identity',
    vars: {
      '--bg': '#fcfcfa',
      '--ink': '#111111',
      '--muted': '#6b6b6b',
      '--line': '#e3e3df',
      '--paper': '#f4f4f1',
      '--accent': '#111111',
      '--art-a': '#1a1a1a',
      '--art-b': '#8c8c8c',
      '--art-c': '#d8d8d4',
      '--art-bg': '#efefec',
    },
  },
  {
    id: 'after-dark',
    name: 'After Dark',
    note: 'Opening-night black',
    vars: {
      '--bg': '#0e0e0e',
      '--ink': '#f1f0ec',
      '--muted': '#9a9a94',
      '--line': '#2a2a28',
      '--paper': '#171716',
      '--accent': '#f1f0ec',
      '--art-a': '#e8e6e0',
      '--art-b': '#7c7b76',
      '--art-c': '#3a3a38',
      '--art-bg': '#1d1d1c',
    },
  },
  {
    id: 'archive',
    name: 'Archive',
    note: 'Warm paper and umber ink',
    vars: {
      '--bg': '#f5efe3',
      '--ink': '#2e2419',
      '--muted': '#86735c',
      '--line': '#e2d7c2',
      '--paper': '#ede4d1',
      '--accent': '#8a3b1e',
      '--art-a': '#3a2c1c',
      '--art-b': '#a86f3e',
      '--art-c': '#d9c8a8',
      '--art-bg': '#e9dfc9',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    note: 'Cyanotype blues',
    vars: {
      '--bg': '#0f1f3d',
      '--ink': '#e9f0fb',
      '--muted': '#8fa4c9',
      '--line': '#22365e',
      '--paper': '#152849',
      '--accent': '#9cc3ff',
      '--art-a': '#dce9ff',
      '--art-b': '#6e93d6',
      '--art-c': '#2c4577',
      '--art-bg': '#16294c',
    },
  },
  {
    id: 'celadon',
    name: 'Celadon',
    note: 'Soft gallery green',
    vars: {
      '--bg': '#eef2ea',
      '--ink': '#1d2a20',
      '--muted': '#5f7363',
      '--line': '#d6e0d2',
      '--paper': '#e3eadd',
      '--accent': '#2f5d3a',
      '--art-a': '#23402c',
      '--art-b': '#6e8f73',
      '--art-c': '#c4d4bf',
      '--art-bg': '#dde6d6',
    },
  },
  {
    id: 'rose',
    name: 'Reading Room',
    note: 'Blush plaster and oxblood',
    vars: {
      '--bg': '#f7eeea',
      '--ink': '#33191c',
      '--muted': '#94686d',
      '--line': '#ead9d4',
      '--paper': '#f0e2dc',
      '--accent': '#7e2230',
      '--art-a': '#491f26',
      '--art-b': '#b4707a',
      '--art-c': '#e3c6c0',
      '--art-bg': '#eddcd5',
    },
  },
  {
    id: 'ultraviolet',
    name: 'Ultraviolet',
    note: 'Late-night esoteric',
    vars: {
      '--bg': '#15101f',
      '--ink': '#efe9f8',
      '--muted': '#9d90b8',
      '--line': '#2c2240',
      '--paper': '#1d1630',
      '--accent': '#c9a4ff',
      '--art-a': '#e6d6ff',
      '--art-b': '#8a68c9',
      '--art-c': '#3c2c61',
      '--art-bg': '#221940',
    },
  },
]

export const DEFAULT_PALETTE_ID = 'gallery'
