export const ADMIN_RESOURCES = [
  { key: 'exhibitions', label: 'Exhibitions', idField: 'slug' },
  { key: 'events', label: 'Events', idField: 'slug' },
  { key: 'artists', label: 'Artists', idField: 'slug' },
  { key: 'works', label: 'Works', idField: 'id' },
  { key: 'opportunities', label: 'Opportunities', idField: 'slug' },
  { key: 'gallery', label: 'Gallery Settings', singleton: true },
]

export const FORM_CONFIGS = {
  artists: {
    title: 'Artist',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true, createOnly: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'discipline', label: 'Discipline', type: 'text' },
      { name: 'seed', label: 'Image seed (fallback)', type: 'text' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'statement', label: 'Statement', type: 'textarea' },
      { name: 'links', label: 'Links (JSON array)', type: 'json' },
      { name: 'exhibitions', label: 'Exhibition slugs (JSON array)', type: 'json' },
    ],
  },
  works: {
    title: 'Work',
    fields: [
      { name: 'id', label: 'ID', type: 'text', required: true, createOnly: true },
      { name: 'artist', label: 'Artist slug', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'medium', label: 'Medium', type: 'text' },
      { name: 'dimensions', label: 'Dimensions', type: 'text' },
      { name: 'price', label: 'Price', type: 'text' },
      { name: 'seed', label: 'Image seed (fallback)', type: 'text' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
    ],
  },
  exhibitions: {
    title: 'Exhibition',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true, createOnly: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'artists', label: 'Artist slugs (JSON array)', type: 'json' },
      { name: 'start', label: 'Start date', type: 'date', required: true },
      { name: 'end', label: 'End date', type: 'date', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['current', 'archive'] },
      { name: 'seed', label: 'Image seed (fallback)', type: 'text' },
      { name: 'imageUrl', label: 'Hero image', type: 'image' },
      { name: 'statement', label: 'Statement', type: 'textarea' },
      { name: 'works', label: 'Work IDs (JSON array)', type: 'json' },
      { name: 'installSeeds', label: 'Install seeds (JSON array)', type: 'json' },
      { name: 'installImages', label: 'Install image URLs (JSON array)', type: 'json' },
    ],
  },
  events: {
    title: 'Event',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true, createOnly: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'text' },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'time', label: 'Time', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'rsvp', label: 'RSVP info', type: 'textarea' },
      { name: 'related', label: 'Related links (JSON object)', type: 'json' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
    ],
  },
  opportunities: {
    title: 'Opportunity',
    fields: [
      { name: 'slug', label: 'Slug', type: 'text', required: true, createOnly: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'kind', label: 'Kind', type: 'text' },
      { name: 'deadline', label: 'Deadline', type: 'date' },
      { name: 'showDates', label: 'Show dates', type: 'text' },
      { name: 'compensation', label: 'Compensation', type: 'textarea' },
      { name: 'process', label: 'Process', type: 'textarea' },
      { name: 'materials', label: 'Materials (JSON array)', type: 'json' },
      { name: 'applyHref', label: 'Apply link', type: 'text' },
      { name: 'statement', label: 'Statement', type: 'textarea' },
      { name: 'imageUrl', label: 'Image', type: 'image' },
    ],
  },
  gallery: {
    title: 'Gallery Settings',
    singleton: true,
    fields: [
      { name: 'name', label: 'Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'instagram', label: 'Instagram handle', type: 'text' },
      { name: 'instagramHref', label: 'Instagram URL', type: 'text' },
      { name: 'address', label: 'Address', type: 'text' },
      { name: 'hours', label: 'Hours', type: 'text' },
      { name: 'mission', label: 'Mission', type: 'textarea' },
      { name: 'philosophy', label: 'Philosophy', type: 'textarea' },
      { name: 'team', label: 'Team (JSON array)', type: 'json' },
    ],
  },
}
